<a href="https://colab.research.google.com/github/Phuc0417/AI_2023/blob/main/AI_w8_24_03_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import Perceptron
x = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,1]

model = Perceptron()
model.fit(x,y)
model.score(x,y)

x1 = [[0.5,0],[0,0.5],[0.6,0],[0,0.6],[-10,2],[0.1,1],[-0.3,4]]
y1 = model.predict(x1)
y1

x2 = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y2 = model.predict(x1)
y2

array([0, 0, 1, 1, 0, 1, 1])

In [ ]:
from sklearn import model_selection
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

iris = datasets.load_iris()

x = iris.data
y= iris.target

print(x[:5])
print(y[:5])

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

sc = StandardScaler()
sc.fit(x_train)

x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

print(x_train, x_train_std)

model = Perceptron(max_iter=10000, eta0=0.1, random_state=0)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
print(y_pred)
print(y_test)
print('độ chính xác mô hình chưa scale: ',accuracy_score(y_test,y_pred))

model = Perceptron(max_iter=10000, eta0=0.1, random_state=0)
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print('độ chính xác mô hình chưa scale: ',accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[[5.  3.4 1.6 0.4]
 [6.4 2.8 5.6 2.1]
 [5.1 3.5 1.4 0.2]
 [5.8 2.8 5.1 2.4]
 [6.1 2.8 4.7 1.2]
 [5.5 2.6 4.4 1.2]
 [5.  3.5 1.3 0.3]
 [5.7 2.8 4.5 1.3]
 [5.2 2.7 3.9 1.4]
 [7.1 3.  5.9 2.1]
 [4.6 3.4 1.4 0.3]
 [6.8 3.  5.5 2.1]
 [4.6 3.6 1.  0.2]
 [7.9 3.8 6.4 2. ]
 [5.  2.3 3.3 1. ]
 [6.1 2.6 5.6 1.4]
 [5.6 3.  4.1 1.3]
 [6.5 2.8 4.6 1.5]
 [6.5 3.  5.5 1.8]
 [5.8 4.  1.2 0.2]
 [6.8 2.8 4.8 1.4]
 [6.7 2.5 5.8 1.8]
 [5.  3.4 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.  2.2 5.  1.5]
 [5.  2.  3.5 1. ]
 [6.3 2.7 4.9 1.8]
 [5.4 3.9 1.7 0.4]
 [6.3 3.4 5.6 2.4]
 [5.4 3.4 1.7 0.2]
 [7.2 3.6 6.1 2.5]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 5.6 2.4]
 [5.6 2.5 3.9 1.1]
 [4.9 3.  1.4 0.2]
 [6.7 3.1 4.4 1.4]
 [6.1 3.  4.6 1.4]
 [5.7 2.8 4.1 1.3]
 [5.1 2.5 3.  1.1]
 [6.  2.7 5.1 1.6]
 [7.7 3.  6.1 2.3]
 [6.4 2.7 5.3 1.9]
 [6.5 3.2 5.1 2. ]
 [5.7 3.  4.2 1.2]
 [4.7 3.2 1.6 0.2]
 [5.4 3.  4.5 1.5]
 [5.5 2.4 3.8 1.1]

In [ ]:

import pandas as pd
import numpy as np
url= '/content/crabs.csv'

data = pd.read_csv(url)

data.head()

data.speies.replace('B','0',inplace=True)
data.speies.replace('O','1',inplace=True)
data.sex.replace('M','1',inplace=True)
data.sex.replace('F','0',inplace=True)

data

x = iris.data
y= iris.target

print(x[:5])
print(y[:5])

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

sc = StandardScaler()
sc.fit(x_train)

x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)

print(x_train, x_train_std)

model = Perceptron(max_iter=10000, eta0=0.1, random_state=0)
model.fit(x_train,y_train)

y_pred = model.predict(x_test)
print(y_pred)
print(y_test)
print('độ chính xác mô hình chưa scale: ',accuracy_score(y_test,y_pred))

model = Perceptron(max_iter=10000, eta0=0.1, random_state=0)
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print('độ chính xác mô hình chưa scale: ',accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
url = '/content/lung_cancer_examples.csv'

df = pd.read_csv(url)

df.head()
df.drop('Name', axis=1, inplace=True)
df.drop('Surname', axis=1, inplace=True)
df.drop('Result', axis=1, inplace=True)
df


Age  Smokes  AreaQ  Alkhol
0    35       3      5       4
1    27      20      2       5
2    30       0      5       2
3    28       0      8       1
4    68       4      5       6
5    34       0     10       0
6    58      15     10       0
7    22      12      5       2
8    45       2      6       0
9    52      18      4       5
10   33       4      8       0
11   18      10      6       3
12   25       2      5       1
13   28      20      2       8
14   34      25      4       8
15   39      18      8       1
16   42      22      3       5
17   19      12      8       0
18   62       5      4       3
19   73      10      7       6
20   55      15      1       3
21   33       8      8       1
22   22      20      6       2
23   44       5      8       1
24   77       3      2       6
25   21      20      5       3
26   37      15      6       2
27   34      12      8       0
28   55      20      1       4
29   40      20      2       7
30   36      13      5       2
31   56      20      3       3
32   47      15      1       8
33   62      25      3       4
34   26      10      7       2
35   25      20      8       2
36   59      20      3       4
37   62      15      5       5
38   33      25      8       2
39   37      10      5       3
40   50      20      2       4
41   47      12      8       0
42   69      20      5       4
43   63      20      4       5
44   39      15      7       2
45   21      20      8       3
46   31      20      9       4
47   28      10      4       1
48   53      20      6       3
49   62      20      5       6
50   42      12      6       2
51   44      30      1       6
52   26      34      1       8
53   35      20      5       1
54   26      13      6       1
55   77      20      5       4
56   75      15      3       5
57   43      30      3       8
58   51      25      9       0

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0